{"uuid": "d9a93f0b-f833-48ef-9738-612242dcc312", "children": ["938ad404-5e5c-4632-bfe4-9455f5a813a1"], "befores": [{"name": "cleanup_after_test", "status": "passed", "start": 1737654131998, "stop": 1737654131998}], "afters": [{"name": "cleanup_after_test::0", "status": "broken", "statusDetails": {"message": "Exception: No se pudo encontrar el botón Home usando los selectores disponibles.\n", "trace": "  File \"C:\\Users\\Augusto  Sanchez\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Augusto  Sanchez\\AppData\\Roaming\\Python\\Python313\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\Augusto  Sanchez\\Desktop\\Testing Projects\\PWC-Challenge\\UI-Testing-Selenium-Python\\conftest.py\", line 39, in cleanup_after_test\n    base_page_obj.go_to_home()\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Augusto  Sanchez\\Desktop\\Testing Projects\\PWC-Challenge\\UI-Testing-Selenium-Python\\page\\base_page.py\", line 49, in go_to_home\n    raise Exception(\"No se pudo encontrar el botón Home usando los selectores disponibles.\")\n"}, "start": 1737654164028, "stop": 1737654240100}], "start": 1737654131998, "stop": 1737654240100}