{"uuid": "9dcb74f8-3b9a-4de0-a91b-b2ae6fc819b9", "children": ["a15a64fb-0354-47dd-8f1e-da38ab771f8d"], "befores": [{"name": "cleanup_after_test", "status": "passed", "start": 1737653512948, "stop": 1737653512948}], "afters": [{"name": "cleanup_after_test::0", "status": "broken", "statusDetails": {"message": "Exception: No se pudo encontrar el botón Home usando los selectores disponibles.\n", "trace": "  File \"C:\\Users\\Augusto  Sanchez\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Augusto  Sanchez\\AppData\\Roaming\\Python\\Python313\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\Augusto  Sanchez\\Desktop\\Testing Projects\\PWC-Challenge\\UI-Testing-Selenium-Python\\conftest.py\", line 39, in cleanup_after_test\n    base_page_obj.go_to_home()\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Augusto  Sanchez\\Desktop\\Testing Projects\\PWC-Challenge\\UI-Testing-Selenium-Python\\page\\base_page.py\", line 49, in go_to_home\n    raise Exception(\"No se pudo encontrar el botón Home usando los selectores disponibles.\")\n"}, "start": 1737653533707, "stop": 1737653609604}], "start": 1737653512948, "stop": 1737653609604}